name: 💬 Auto Comment

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened, closed]

jobs:
  auto_comment:
    runs-on: ubuntu-latest
    steps:
      - name: 🤖 Auto Comment on Issues and PRs
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const { owner, repo } = context.repo;
            const author = context.payload.sender.login;
            
            if (context.eventName === 'issues' && context.payload.action === 'opened') {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner,
                repo,
                body: `Hey @${author}! 👋 Thanks for flagging this! 🐛🐞

            Before we dig in, Let's make sure you have

            🔍 Gone through the documentation: https://rengine.wiki
            🕵️ Make sure it's not a known issue
            📝 Provided us all the details related to this bug`
              });
            } else if (context.eventName === 'pull_request' && context.payload.action === 'opened') {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner,
                repo,
                body: `Woohoo @${author}! 🎉 You've just dropped some hot new code! 🔥

            Hang tight while we review this! You rock! 🤘`
              });
            } else if (context.eventName === 'pull_request' && context.payload.action === 'closed') {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner,
                repo,
                body: `Holy smokes, @${author}! 🤯 You've just made reNgine even more awesome!

            Your code is now part of the reNgine hall of fame. 🏆 
            
            Keep the cool ideas coming - maybe next time you'll break the internet! 💻💥

            Virtual high fives all around! 🙌`
              });
            }